[profile.release-with-debug]
inherits = "release"
debug = true

[package]
name = "wlx-overlay-s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
ash = "^0.37.2"
ash-window = "0.12.0"
chrono = "0.4.29"
chrono-tz = "0.8.5"
cstr = "0.2.11"
ctrlc = { version = "3.4.2", features = ["termination"] }
env_logger = "0.10.0"
fontconfig-rs = "0.1.1"
freetype-rs = "0.32.0"
futures = "0.3.29"
glam = { version = "0.24.1", features = ["approx"] }
idmap = "0.2.21"
idmap-derive = "0.1.2"
input-linux = "0.6.0"
json = { version = "0.12.4", optional = true }
libc = "0.2.147"
log = "0.4.20"
once_cell = "1.18.0"
openxr = { version = "0.17.1", features = ["linked"], optional = true }
ovr_overlay = { features = ["ovr_input", "ovr_system"], git = "https://github.com/galister/ovr_overlay_oyasumi", optional = true }
png = "0.17.10"
raw-window-handle = "0.5.2"
regex = "1.9.5"
rodio = { version = "0.17.1", default-features = false, features = ["wav", "hound"] }
rosc = { version = "0.10.1", optional = true }
serde = { version = "1.0.188", features = ["derive", "rc"] }
serde_json = "1.0.113"
serde_yaml = "0.9.25"
smallvec = "1.11.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.56"
vulkano = { git = "https://github.com/vulkano-rs/vulkano", rev = "94f50f1" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano", rev = "94f50f1" }
winit = "0.29.10"
wlx-capture = { git = "https://github.com/galister/wlx-capture" }
xdg = "2.5.2"

[features]
openvr = ["dep:ovr_overlay", "dep:json"]
openxr = ["dep:openxr"]
osc = ["dep:rosc"]
default = ["openvr", "openxr", "osc"]

